// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9eenpui3jiJdZmvdu5ViLSFPOIJhZ5lQ',
    appId: '1:385786897798:web:17c7277a0505a5aeadf807',
    messagingSenderId: '385786897798',
    projectId: 'fir-demo-8f2cc',
    authDomain: 'fir-demo-8f2cc.firebaseapp.com',
    storageBucket: 'fir-demo-8f2cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASisf1wGTV0tYKDASPZ00xlVIDoU0s9yA',
    appId: '1:385786897798:android:775882ec112f84fdadf807',
    messagingSenderId: '385786897798',
    projectId: 'fir-demo-8f2cc',
    storageBucket: 'fir-demo-8f2cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkz0yfGQiDAWJaw8eid-4ZWKeF5ry1zY0',
    appId: '1:385786897798:ios:758f24e0ca63f3f5adf807',
    messagingSenderId: '385786897798',
    projectId: 'fir-demo-8f2cc',
    storageBucket: 'fir-demo-8f2cc.appspot.com',
    iosClientId: '385786897798-0t0alliiterr36hc3cjnkdlm9fkmecfj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseDemo',
  );
}
